// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9hguEZNXwGpu6SKF_SKXehMAkcMOPnbE',
    appId: '1:977130354207:web:10cab0e6ad459afc8a872a',
    messagingSenderId: '977130354207',
    projectId: 'computic-1fbfd',
    authDomain: 'computic-1fbfd.firebaseapp.com',
    storageBucket: 'computic-1fbfd.appspot.com',
    measurementId: 'G-KFZX2NNY6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0rMMKhw9npYxfskDHasOQnYXZXpJicDw',
    appId: '1:977130354207:android:c906db98a36c910e8a872a',
    messagingSenderId: '977130354207',
    projectId: 'computic-1fbfd',
    storageBucket: 'computic-1fbfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Qvrl7MJRnNp4twyH0fF72DnYrZBeWxw',
    appId: '1:977130354207:ios:e702d0a2d349700f8a872a',
    messagingSenderId: '977130354207',
    projectId: 'computic-1fbfd',
    storageBucket: 'computic-1fbfd.appspot.com',
    iosBundleId: 'com.example.computic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Qvrl7MJRnNp4twyH0fF72DnYrZBeWxw',
    appId: '1:977130354207:ios:e702d0a2d349700f8a872a',
    messagingSenderId: '977130354207',
    projectId: 'computic-1fbfd',
    storageBucket: 'computic-1fbfd.appspot.com',
    iosBundleId: 'com.example.computic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9hguEZNXwGpu6SKF_SKXehMAkcMOPnbE',
    appId: '1:977130354207:web:845b765afab404688a872a',
    messagingSenderId: '977130354207',
    projectId: 'computic-1fbfd',
    authDomain: 'computic-1fbfd.firebaseapp.com',
    storageBucket: 'computic-1fbfd.appspot.com',
    measurementId: 'G-7D3BP9KVMC',
  );

}